window.AFGHAN_EATS_CONFIG = {
  apiBaseUrl: 'https://afghaneats-api.onrender.com',
  supportPhone: '+93 796 851 968',
  supportEmail: 'support@afghaneats.net',
  customerAndroidPackage: 'com.app.afghaneatsmobile',
  customerAndroidUrl: '',
  customerIosUrl: '',
  launchCity: 'Herat'
};

(function prepareCustomerLocale(){const fa=localStorage.getItem('ae_lang')==='fa';document.documentElement.lang=fa?'fa':'en';document.documentElement.dir=fa?'rtl':'ltr';document.documentElement.dataset.aeLocaleReady='1'})();
(function loadAccessibilityV39(){const script=document.createElement('script');script.src='/assets/accessibility.js';script.async=true;script.dataset.aeAccessibilityV39='1';document.head.appendChild(script)})();
(function loadMerchantOperations(){const path=location.pathname.toLowerCase(),owner=path.endsWith('/owner.html')||path==='/owner',customer=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/restaurant.html')||path.endsWith('/checkout.html'),src=owner?'/assets/merchant-owner.js':customer?'/assets/merchant.js?v=20260905-3':'';if(!src)return;const script=document.createElement('script');script.src=src;script.async=true;script.dataset.aeMerchantModule='1';document.head.appendChild(script)})();
(function loadDispatchIntelligence(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/operations.html')||path.endsWith('/owner.html')||path.endsWith('/rider-portal.html')||path.endsWith('/order.html')||path==='/operations'||path==='/owner'||path==='/rider-portal'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/dispatch.js';script.async=true;script.dataset.aeDispatchModule='1';document.head.appendChild(script)})();
(function loadLastMilePrecision(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/operations.html')||path.endsWith('/rider-portal.html')||path.endsWith('/order.html')||path==='/operations'||path==='/rider-portal'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/lastmile.js';script.async=true;script.dataset.aeLastMileModule='1';document.head.appendChild(script)})();
(function loadMarketplaceIntegrity(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/integrity.js';script.async=true;script.dataset.aeIntegrityModule='1';document.head.appendChild(script)})();
(function loadPlatformStatus(){const script=document.createElement('script');script.src='/assets/platform-status.js';script.async=true;script.dataset.aePlatformStatus='1';document.head.appendChild(script)})();
(function loadCityContext(){const script=document.createElement('script');script.src='/assets/cities.js?v=20260905-3';script.async=true;script.dataset.aeCityModule='1';document.head.appendChild(script)})();
(function loadMerchantQuality(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/operations.html')||path.endsWith('/owner.html')||path==='/operations'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/quality.js';script.async=true;script.dataset.aeMerchantQuality='1';document.head.appendChild(script)})();
(function loadCatalogStudio(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path==='/restaurant'||path==='/checkout'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/catalog.js';script.async=true;script.dataset.aeCatalogModule='1';document.head.appendChild(script)})();
(function loadLiveDiscovery(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html');if(!enabled)return;const script=document.createElement('script');script.src='/assets/live-search.js';script.async=true;script.dataset.aeLiveDiscovery='1';document.head.appendChild(script)})();
(function loadRewardsRedemption(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/checkout.html')||path.endsWith('/operations.html')||path==='/checkout'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/rewards.js';script.async=true;script.dataset.aeRewardsModule='1';document.head.appendChild(script)})();
(function loadOrderRecovery(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/order.html')||path.endsWith('/owner.html')||path==='/order'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/recovery.js';script.async=true;script.dataset.aeRecoveryModule='1';document.head.appendChild(script)})();
(function loadGroupOrdering(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/order.html')||path==='/restaurant'||path==='/checkout'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/group-order.js';script.async=true;script.dataset.aeGroupOrderModule='1';document.head.appendChild(script)})();
(function loadRealtimeOrderTimeline(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/order.html')||path.endsWith('/owner.html')||path.endsWith('/rider-portal.html')||path.endsWith('/operations.html')||path==='/order'||path==='/owner'||path==='/rider-portal'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/timeline.js';script.async=true;script.dataset.aeTimelineModule='1';document.head.appendChild(script)})();
(function loadSmartScheduling(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path==='/checkout'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/scheduling.js';script.async=true;script.dataset.aeSchedulingModule='1';document.head.appendChild(script)})();
(function loadPersonalizedHome(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html');if(!enabled)return;const script=document.createElement('script');script.src='/assets/personalization.js?v=20260905-2';script.async=true;script.dataset.aePersonalizationModule='1';document.head.appendChild(script)})();
(function loadSupportResolution(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/help.html')||path.endsWith('/account.html')||path.endsWith('/operations.html')||path==='/help'||path==='/account'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/support-resolution.js';script.async=true;script.dataset.aeSupportResolution='1';document.head.appendChild(script)})();
(function prepareGrowthLayout(){document.addEventListener('DOMContentLoaded',()=>document.querySelector('.container.menu-layout')?.classList.add('restaurant-layout'))})();
(function loadMerchantGrowth(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/restaurants'||path==='/restaurant'||path==='/checkout'||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/growth.js';script.async=true;script.dataset.aeGrowthModule='1';document.head.appendChild(script)})();
(function loadMerchantFinanceV30(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/merchant-finance-v30.js';script.async=true;script.dataset.aeMerchantFinanceV30='1';document.head.appendChild(script)})();
(function loadCompensationV31(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/help.html')||path.endsWith('/account.html')||path.endsWith('/checkout.html')||path.endsWith('/operations.html')||path==='/help'||path==='/account'||path==='/checkout'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/compensation.js';script.async=true;script.dataset.aeCompensationV31='1';document.head.appendChild(script)})();
(function loadFoodSafetyV32(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/account.html')||path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/restaurant'||path==='/checkout'||path==='/account'||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/food-safety.js';script.async=true;script.dataset.aeFoodSafetyV32='1';document.head.appendChild(script)})();
(function loadKitchenV33(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/owner.html')||path.endsWith('/rider-portal.html')||path.endsWith('/order.html')||path.endsWith('/operations.html')||path==='/owner'||path==='/rider-portal'||path==='/order'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/kitchen.js';script.async=true;script.dataset.aeKitchenV33='1';document.head.appendChild(script)})();
(function loadDemandForecastV34(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/forecast.js';script.async=true;script.dataset.aeDemandForecastV34='1';document.head.appendChild(script)})();
(function loadInventoryV35(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/restaurant'||path==='/checkout'||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/inventory.js';script.async=true;script.dataset.aeInventoryV35='1';document.head.appendChild(script)})();
(function loadObservabilityV36(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/observability.js';script.async=true;script.dataset.aeObservabilityV36='1';document.head.appendChild(script)})();
(function loadDataReadinessV37(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/account.html')||path.endsWith('/operations.html')||path==='/account'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/data-readiness.js';script.async=true;script.dataset.aeDataReadinessV37='1';document.head.appendChild(script)})();
(function loadSecurityPostureV38(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/security-posture.js';script.async=true;script.dataset.aeSecurityPostureV38='1';document.head.appendChild(script)})();
(function loadLaunchReadinessV40(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/launch-readiness.js';script.async=true;script.dataset.aeLaunchReadinessV40='1';document.head.appendChild(script)})();
(function loadRestaurantClaimsV48(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/claims.js';script.async=true;script.dataset.aeRestaurantClaimsV48='1';document.head.appendChild(script)})();
(function loadIdentityV53(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/account.html')||path.endsWith('/rider.html')||path.endsWith('/rider-portal.html')||path==='/account'||path==='/rider'||path==='/rider-portal';if(!enabled)return;const script=document.createElement('script');script.src='/assets/identity.js';script.defer=true;script.dataset.aeIdentityV53='1';document.head.appendChild(script)})();
