window.AFGHAN_EATS_CONFIG = {
  apiBaseUrl: 'https://afghaneats-api.onrender.com',
  supportPhone: '+93 796 851 968',
  supportEmail: 'support@afghaneats.net',
  launchCity: 'Herat'
};

(function loadMerchantOperations(){const path=location.pathname.toLowerCase(),owner=path.endsWith('/owner.html')||path==='/owner',customer=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/restaurant.html')||path.endsWith('/checkout.html'),src=owner?'/assets/merchant-owner.js':customer?'/assets/merchant.js':'';if(!src)return;const script=document.createElement('script');script.src=src;script.async=true;script.dataset.aeMerchantModule='1';document.head.appendChild(script)})();
(function loadDispatchIntelligence(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/operations.html')||path.endsWith('/owner.html')||path.endsWith('/rider-portal.html')||path.endsWith('/order.html')||path==='/operations'||path==='/owner'||path==='/rider-portal'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/dispatch.js';script.async=true;script.dataset.aeDispatchModule='1';document.head.appendChild(script)})();
(function loadLastMilePrecision(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/operations.html')||path.endsWith('/rider-portal.html')||path.endsWith('/order.html')||path==='/operations'||path==='/rider-portal'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/lastmile.js';script.async=true;script.dataset.aeLastMileModule='1';document.head.appendChild(script)})();
(function loadMarketplaceIntegrity(){const path=location.pathname.toLowerCase();if(!(path.endsWith('/operations.html')||path==='/operations'))return;const script=document.createElement('script');script.src='/assets/integrity.js';script.async=true;script.dataset.aeIntegrityModule='1';document.head.appendChild(script)})();
(function loadPlatformStatus(){const script=document.createElement('script');script.src='/assets/platform-status.js';script.async=true;script.dataset.aePlatformStatus='1';document.head.appendChild(script)})();
(function loadCityContext(){const script=document.createElement('script');script.src='/assets/cities.js';script.async=true;script.dataset.aeCityModule='1';document.head.appendChild(script)})();
(function loadMerchantQuality(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/operations.html')||path.endsWith('/owner.html')||path==='/operations'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/quality.js';script.async=true;script.dataset.aeQualityModule='1';document.head.appendChild(script)})();
(function loadCatalogStudio(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path==='/restaurant'||path==='/checkout'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/catalog.js';script.async=true;script.dataset.aeCatalogModule='1';document.head.appendChild(script)})();
(function loadLiveDiscovery(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path==='/restaurants';if(!enabled)return;const script=document.createElement('script');script.src='/assets/live-search.js';script.async=true;script.dataset.aeLiveDiscovery='1';document.head.appendChild(script)})();
(function loadRewardsRedemption(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/checkout.html')||path.endsWith('/operations.html')||path==='/checkout'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/rewards.js';script.async=true;script.dataset.aeRewardsModule='1';document.head.appendChild(script)})();
(function loadOrderRecovery(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/order.html')||path.endsWith('/owner.html')||path==='/order'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/recovery.js';script.async=true;script.dataset.aeRecoveryModule='1';document.head.appendChild(script)})();
(function loadGroupOrdering(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/order.html')||path==='/restaurant'||path==='/checkout'||path==='/order';if(!enabled)return;const script=document.createElement('script');script.src='/assets/group-order.js';script.async=true;script.dataset.aeGroupOrderModule='1';document.head.appendChild(script)})();
(function loadRealtimeOrderTimeline(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/order.html')||path.endsWith('/owner.html')||path.endsWith('/rider-portal.html')||path.endsWith('/operations.html')||path==='/order'||path==='/owner'||path==='/rider-portal'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/timeline.js';script.async=true;script.dataset.aeTimelineModule='1';document.head.appendChild(script)})();
(function loadSmartScheduling(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path==='/checkout'||path==='/owner';if(!enabled)return;const script=document.createElement('script');script.src='/assets/scheduling.js';script.async=true;script.dataset.aeSchedulingModule='1';document.head.appendChild(script)})();
(function loadPersonalizedHome(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html');if(!enabled)return;const script=document.createElement('script');script.src='/assets/personalization.js';script.async=true;script.dataset.aePersonalizationModule='1';document.head.appendChild(script)})();
(function loadSupportResolution(){const path=location.pathname.toLowerCase(),enabled=path.endsWith('/help.html')||path.endsWith('/account.html')||path.endsWith('/operations.html')||path==='/help'||path==='/account'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/support-resolution.js';script.async=true;script.dataset.aeSupportResolution='1';document.head.appendChild(script)})();
(function prepareGrowthLayout(){document.addEventListener('DOMContentLoaded',()=>document.querySelector('.container.menu-layout')?.classList.add('restaurant-layout'))})();
(function loadMerchantGrowth(){const path=location.pathname.toLowerCase(),enabled=path==='/'||path.endsWith('/index.html')||path.endsWith('/restaurants.html')||path.endsWith('/restaurant.html')||path.endsWith('/checkout.html')||path.endsWith('/owner.html')||path.endsWith('/operations.html')||path==='/restaurants'||path==='/restaurant'||path==='/checkout'||path==='/owner'||path==='/operations';if(!enabled)return;const script=document.createElement('script');script.src='/assets/growth.js';script.async=true;script.dataset.aeGrowthModule='1';document.head.appendChild(script)})();
